### ISSUE TITLE
extend TypedRecord using Type alias

### ISSUE THREAD

**Issue by eddedd88** [rangle/typed-immutable-record#22]
I was wondering if I could create my Record interface from a Type alias instead of an interface.

The reason I am doing this is because I want to use "[discrimated unions](https://basarat.gitbooks.io/typescript/content/docs/types/discriminated-unions.html)" that typescript supports

Currently I can only extend from another interface or class, for example:

```
interface IAnimal {
     ...
}

interface IAnimalRecord extends TypedRecord<IAnimalRecord>, IAnimal {}
```

I would like IAnimal to be a Type

```
interface IDog {}
interface ICat {}

type IAnimal = IDog | ICat;

type AnimalRecord = TypedRecord of IAnimal (???)
```

**Comment by danielfigueiredo** [comment]
Ok, considering the following declaration
```typescript
  interface IDog {
    drool: boolean;
  }

  interface ICat {
    purr: boolean;
  } 

  type IAnimal = IDog | ICat;
```
you can't do 

```typescript
  interface IAnimalRecord extends TypedRecord<IAnimalRecord>, IAnimal {}
```
because typescript will say "Interfaces can only extend other interfaces or classes"

then you try to do this:

```typescript
  type IAnimalRecord = TypedRecord<IAnimalRecord> & IAnimal;
```

and you get "Type alias 'IAnimalRecord' circularly references itself. (2456)"

no dice

that said, if you could cheat doing

```typescript
  type IAnimalRecord = TypedRecord<any> & IAnimal;

  describe('When using discrimated unions', () => {
    it('should be able to generate a typed record', () => {
      const dog = makeTypedFactory<IAnimal, IAnimalRecord>({
        drool: true
      });
      const cat = makeTypedFactory<IAnimal, IAnimalRecord>({
        purr: true  
      });
      const err = makeTypedFactory<IAnimal, IAnimalRecord>({
        errorField: 'aaaa'
      });
    });
  });
```

that will work, and will throw error only when evaluating 

```typescript
      const err = makeTypedFactory<IAnimal, IAnimalRecord>({
        errorField: 'aaaa'
      });
```
because `errorField` is not either ICat or IDog
however, using any for the typed record won't make your record restrict to the js (ICat or IDog) type when performing immutable operations..
I can't find a way to do this with Typescript. Will try to think more about it

**Comment by danielfigueiredo** [comment]
Could we consider this closed?
