### ISSUE TITLE
use case for recordify

### ISSUE THREAD

**Issue by SethDavenport** [rangle/typed-immutable-record#5]
Just curious - what's the use case for recordify?  I'll probably use recordFactory in almost all cases.

**Comment by danielfigueiredo** [comment]
sometimes you don't care about the default values of a record or you care but you have no need for holding the factory. For example, you fetch some data from an api you want that directly as a record so that you can use in the ui
It is really just a utility so you can create a typedrecord with a single call

**Comment by danielfigueiredo** [comment]
I'm closing this for now please feel free to reopen if you have anything else
